# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 'git push --prune https://$(ghPat)@github.com/hong-revo/testrepo +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*'
  displayName: 'Copy to mirror repo'

